general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 0
    no_fade_in = false
}

auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
    }
}

background {
    monitor =
    path = ~/.local/share/wallpapers/black-black.png

    blur_passes = 0
    blur_size = 0
    noise = 0.0
}

input-field {
    monitor =
    size = 520, 85
    outline_thickness = 3

    dots_size = 0.30
    dots_spacing = 0.25
    dots_center = true

    # bg / glass
    outer_color = #000000
    inner_color = #000000

    # text
    font_color = #ffffff
    check_color = #000000
    fail_color = #000000
    capslock_color = #000000

    fade_on_empty = true
    hide_input = false

    placeholder_text = <span foreground="grey">Enter Password</span>

    position = 0, -120
    halign = center
    valign = center
}


